apiVersion: v1
kind: Pod
metadata:
  name: small-pod
  labels:
    app: guestbook
    tier: frontend
  uid: 65b9cb96-fadf-11e9-ab76-0cc47a750aba
spec:
  containers:
    - name: php-redis
      image: gcr.io/google-samples/gb-frontend:v4
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 150m
          memory: 100Mi
          nvidia.com/gpu: 1
        requests:
          cpu: 150m
          memory: 100Mi
          nvidia.com/gpu: 1
  restartPolicy: "OnFailure"
  dnsPolicy: "Default"
  schedulerName: default-scheduler